import { Report } from "../Report";
import { ReportConfiguration } from "../../config/ReportConfiguration";
import { ReleaseViewModel } from "./ReleaseViewModel";
import { PhaseViewModelWrapper } from "./PhaseViewModel";
import { PhaseIssuesViewModel } from "./PhaseIssuesViewModel";
import { TestResultSummaryViewModel } from "./TestResultSummaryViewModel";
import { ArtifactViewModelWrapper } from "./ArtifactViewModel";
import { ChangeViewModelWrapper } from "./ChangeViewModel";
import { TestSummaryGroupViewModelWrapper } from "./TestSummaryGroupViewModel";
import { TestResultsGroupViewModelWrapper } from "./TestResultsGroupViewModel";
export declare class EmailReportViewModel {
    DataMissing: boolean;
    HasTestResultsToShow: boolean;
    HasFailedTests: boolean;
    HasFilteredTests: boolean;
    HasTaskFailures: boolean;
    HasCanceledPhases: boolean;
    MaxTestResultsToShow: number;
    ProjectName: string;
    Release: ReleaseViewModel;
    Build: any;
    Phases: PhaseViewModelWrapper;
    PhaseIssuesSummary: PhaseIssuesViewModel;
    AllTests: TestResultSummaryViewModel;
    Artifacts: ArtifactViewModelWrapper;
    AssociatedChanges: ChangeViewModelWrapper;
    SummaryGroups: TestSummaryGroupViewModelWrapper;
    TestResultsGroups: TestResultsGroupViewModelWrapper;
    TestTabLink: string;
    ShowAssociatedChanges: boolean;
    constructor(report: Report, reportConfiguration: ReportConfiguration);
    private InitializePhases;
    private SetMailSubject;
    private InitializeAssociatedChanges;
    private InitializeSummaryGroupViewModel;
    private InitializeTestResultGroups;
    private GetPassPercentage;
}
